### ISSUE TITLE
LED

### ISSUE THREAD

**Issue by Ido-Sobol** [FTC-ORBIT/14029-Powerplay#24]
(Colors can be changed, it is just a concept)

Travel - blue
Intake - green
Emission - purple

When we detect gamepiece, blink white for 200 ms.

When there is gamepiece in the robot blink slowly.

When we are auto-aiming for the bar and we are in the correct position blink fast.

**Comment by Ido-Sobol** [comment]
@Bar2005  
Who is on it?

**Comment by Bar2005** [comment]
@AsafAzran

**Comment by Ido-Sobol** [comment]
#56
