### ISSUE TITLE
write testMotor(s) function to the configuration when first getting the robot

### ISSUE THREAD

**Issue by Bar2005** [FTC-ORBIT/14029-Powerplay#51]
write it in a separated classes related to the motor you are testing (elevatorMotorTest will be written in Elevator Class)

**Comment by Ido-Sobol** [comment]
I didn't understand what you have meant...

we don't really need a lot of opmodes since the only thing we will be tuning is the elvator (all of the other motors are powered by percent output like intake, we will tune the drivetrain with the road runner and servo does not need to be tuned.

**Comment by Bar2005** [comment]
What I meant is that we need to know if to reverse the motors or not
We will do that by simply give a power to each motor and see if it turns the right direction. If not, we will reverse it
The second reason is for the configuration, in case we don't know which motor is at which port. This function will help us understand it and will make our life much easier in the configuration part.
Tell me if you think I got it wrong

**Comment by Bar2005** [comment]
It we add OpModes, we will simply call this functions in Robot )and then delete them as soon as we finish the task)
